name: Cypress E2E Tests Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm test

      - name: Upload Test Reports Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-reports
          path: cypress/reports/
          retention-days: 7